 import '../../model/ChatModel.dart';

List<ChatModel> chatData = [
    ChatModel(
      name: "Sahil",
      currentMessage: "I am Sahil, can you visit this website?",
      time: "12:14",
      icon: 'assets/images/google.png',
      status: "online",
      id: 1,
    ),
    ChatModel(
      name: "Aisha",
      currentMessage: "Hi, how are you doing?",
      time: "12:15",
      icon: 'assets/images/google.png',
      status: "offline",
      id: 2,
    ),
    ChatModel(
      name: "John",
      currentMessage: "Don't forget our meeting at 3 PM.",
      time: "12:16",
      icon: 'assets/images/google.png',
      status: "busy",
      id: 3,
    ),
    ChatModel(
      name: "Emma",
      currentMessage: "Can you review my code?",
      time: "12:17",
      icon: 'assets/images/google.png',
      status: "online",
      id: 4,
    ),
    ChatModel(
      name: "Mike",
      currentMessage: "Happy Birthday!",
      time: "12:18",
      icon: 'assets/images/google.png',
      status: "offline",
      id: 5,
    ),
    ChatModel(
      name: "Olivia",
      currentMessage: "Let's catch up later.",
      time: "12:19",
      icon: 'assets/images/google.png',
      status: "away",
      id: 6,
    ),
    ChatModel(
      name: "Liam",
      currentMessage: "I've sent you the files.",
      time: "12:20",
      icon: 'assets/images/google.png',
      status: "online",
      id: 7,
    ),
    ChatModel(
      name: "Sophia",
      currentMessage: "Thank you!",
      time: "12:21",
      icon: 'assets/images/google.png',
      status: "offline",
      id: 8,
    ),
    ChatModel(
      name: "William",
      currentMessage: "Where are you?",
      time: "12:22",
      icon: 'assets/images/google.png',
      status: "busy",
      id: 9,
    ),
    ChatModel(
      name: "Ava",
      currentMessage: "Can we reschedule?",
      time: "12:23",
      icon: 'assets/images/google.png',
      status: "online",
      id: 10,
    ),
    ChatModel(
      name: "James",
      currentMessage: "Meeting has been postponed.",
      time: "12:24",
      icon: 'assets/images/google.png',
      status: "offline",
      id: 11,
    ),
    ChatModel(
      name: "Mia",
      currentMessage: "See you tomorrow!",
      time: "12:25",
      icon: 'assets/images/google.png',
      status: "online",
      id: 12,
    ),
    ChatModel(
      name: "Noah",
      currentMessage: "Let's have lunch together.",
      time: "12:26",
      icon: 'assets/images/google.png',
      status: "away",
      id: 13,
    ),
    ChatModel(
      name: "Amelia",
      currentMessage: "Can you help me with this project?",
      time: "12:27",
      icon: 'assets/images/google.png',
      status: "online",
      id: 14,
    ),
    ChatModel(
      name: "Logan",
      currentMessage: "Please check your email.",
      time: "12:28",
      icon: 'assets/images/google.png',
      status: "busy",
      id: 15,
    ),
    ChatModel(
      name: "Charlotte",
      currentMessage: "Let's meet at 5 PM.",
      time: "12:29",
      icon: 'assets/images/google.png',
      status: "offline",
      id: 16,
    ),
    ChatModel(
      name: "Lucas",
      currentMessage: "Good morning!",
      time: "12:30",
      icon: 'assets/images/google.png',
      status: "online",
      id: 17,
    ),
    ChatModel(
      name: "Harper",
      currentMessage: "Can we talk?",
      time: "12:31",
      icon: 'assets/images/google.png',
      status: "offline",
      id: 18,
    ),
    ChatModel(
      name: "Mason",
      currentMessage: "I've completed the task.",
      time: "12:32",
      icon: 'assets/images/google.png',
      status: "online",
      id: 19,
    ),
    ChatModel(
      name: "Ella",
      currentMessage: "What's the update on the project?",
      time: "12:33",
      icon: 'assets/images/google.png',
      status: "busy",
      id: 20,
    ),
  ];
